replicasCount: 1
fullName: "invicta-ms-interactions"
selectorLabel: "invicta-ms-interactions"

service:
  postgresql: 5432

containers:
  hs_adapter:
    name: hs-postgres
    image: registry.alexstorm.solenopsys.org/alexstorm-hsm-postgres
    pullPolicy: Always

